# ============================================================================
# Auralynq — Windows launcher (PowerShell)
# Requires: Podman Desktop OR Docker Desktop (either works)
#
# Usage:
#   .\start-podman.ps1 -Build          # first time — builds images then starts
#   .\start-podman.ps1 -Build -NoCache # clean rebuild (slower)
#   .\start-podman.ps1                 # subsequent runs — just start
#
# Access: https://localhost:8443
#   (self-signed cert → "Advanced" → "Proceed to localhost")
# ============================================================================

param(
    [switch]$Build,
    [switch]$NoCache
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$Repo   = Split-Path -Parent $MyInvocation.MyCommand.Definition
$EnvFile = Join-Path $Repo ".env.podman.windows"

# ── Pick container engine ────────────────────────────────────────────────────
$Engine = ""
if (Get-Command podman -ErrorAction SilentlyContinue) {
    $Engine = "podman"
} elseif (Get-Command docker -ErrorAction SilentlyContinue) {
    $Engine = "docker"
} else {
    Write-Error "Neither podman nor docker found. Install Podman Desktop or Docker Desktop."
    exit 1
}

$ComposeCmd = if ($Engine -eq "podman") { "podman-compose" } else { "docker" }
$ComposeSub = if ($Engine -eq "podman") { "" } else { "compose" }

Write-Host "→  Using container engine: $Engine" -ForegroundColor Cyan

# ── Helper: wait for TCP port ────────────────────────────────────────────────
function Wait-Port($host, $port, $name, $retries = 30) {
    $n = 0
    while ($n -lt $retries) {
        try {
            $tcp = New-Object Net.Sockets.TcpClient
            $tcp.Connect($host, $port)
            $tcp.Close()
            Write-Host "✓  $name is up on :$port" -ForegroundColor Green
            return
        } catch {}
        $n++; Start-Sleep 1
    }
    throw "$name did not open port $port after ${retries}s"
}

# ── 1. Ollama: rebind to 0.0.0.0 ─────────────────────────────────────────────
# Containers reach the host via host.containers.internal (Podman) or
# host-gateway (Docker). Ollama must listen on 0.0.0.0, not 127.0.0.1.
Write-Host "→  Restarting Ollama on 0.0.0.0:11434 …" -ForegroundColor Cyan

# Stop any running Ollama instance
$ollamaProc = Get-Process -Name "ollama" -ErrorAction SilentlyContinue
if ($ollamaProc) {
    $ollamaProc | Stop-Process -Force
    Start-Sleep 1
}

$env:OLLAMA_HOST = "0.0.0.0"
Start-Process -FilePath "ollama" -ArgumentList "serve" -WindowStyle Hidden -PassThru | Out-Null
Wait-Port "127.0.0.1" 11434 "Ollama"

# ── 2. Create Windows-specific .env.podman.windows ────────────────────────────
$envContent = @"
# Auralynq Podman/Docker — Windows (localhost) configuration
# Generated by start-podman.ps1 — edit manually if needed

AURALYNQ_CERT_HOST=localhost
AURALYNQ_SITE_ADDRESS=:8443
AURALYNQ_HTTPS_PORT=8443
AURALYNQ_TLS=/certs/site.crt /certs/site.key
AURALYNQ_WEB_UPSTREAM=http://auralynq-web:3000

# Bind all services to loopback (access via Caddy on 8443 only)
AURALYNQ_BIND_INTERNAL=127.0.0.1
AURALYNQ_API_PORT=8100
AURALYNQ_QDRANT_HTTP_PORT=6433
AURALYNQ_QDRANT_GRPC_PORT=6434
AURALYNQ_WEB_PORT=3800
AURALYNQ_PHOENIX_PORT=6006
AURALYNQ_PHOENIX_OTLP_PORT=4317
AURALYNQ_MCP_PORT=8765

# LLM — Ollama on host, reachable from containers via host magic DNS
# Podman Desktop:  host.containers.internal
# Docker Desktop:  host-gateway (resolved via extra_hosts in compose)
AURALYNQ_LLM__PROVIDER=auto
AURALYNQ_LLM__MODEL=qwen3:32b
AURALYNQ_LLM__BASE_URL=http://host.containers.internal:11434

AURALYNQ_EMBEDDING__PROVIDER=auto
AURALYNQ_EMBEDDING__OLLAMA_MODEL=nomic-embed-text

AURALYNQ_VECTOR_URL=http://auralynq-qdrant:6333
AURALYNQ_VECTOR_BACKEND=qdrant

AURALYNQ_SERVE__API_KEY=
AURALYNQ_SERVE__CORS_ORIGINS=["https://localhost:8443"]

AURALYNQ_API_INTERNAL=http://auralynq-api:8000
AURALYNQ_OTLP_ENDPOINT=http://auralynq-phoenix:4317

ANTHROPIC_API_KEY=
OPENAI_API_KEY=
COHERE_API_KEY=
HUGGINGFACE_TOKEN=

AURALYNQ_IMAGE_PREFIX=localhost/auralynq-
AURALYNQ_IMAGE_TAG=0.2.0
"@
Set-Content -Path $EnvFile -Value $envContent -Encoding UTF8
Write-Host "✓  Created $EnvFile" -ForegroundColor Green

# ── 3. Build images ────────────────────────────────────────────────────────────
if ($Build) {
    $cacheFlag = if ($NoCache) { "--no-cache" } else { "" }
    $prefix    = "localhost/auralynq-"
    $tag       = "0.2.0"

    Write-Host "→  Building caddy image (cert host: localhost) …" -ForegroundColor Cyan
    $buildArgs = @("build", "--build-arg", "AURALYNQ_CERT_HOST=localhost",
                   "-f", (Join-Path $Repo "containers\caddy.Dockerfile"),
                   "-t", "${prefix}caddy:${tag}", $Repo)
    if ($cacheFlag) { $buildArgs = @($cacheFlag) + $buildArgs }
    & $Engine @buildArgs
    Write-Host "✓  caddy built" -ForegroundColor Green

    Write-Host "→  Building api image …" -ForegroundColor Cyan
    $buildArgs = @("build", "-f", (Join-Path $Repo "containers\api.Dockerfile"),
                   "-t", "${prefix}api:${tag}", $Repo)
    if ($cacheFlag) { $buildArgs = @($cacheFlag) + $buildArgs }
    & $Engine @buildArgs
    Write-Host "✓  api built" -ForegroundColor Green

    Write-Host "→  Building web image …" -ForegroundColor Cyan
    $buildArgs = @("build", "--build-arg", "NEXT_PUBLIC_API_BASE=/api",
                   "-f", (Join-Path $Repo "containers\web.Dockerfile"),
                   "-t", "${prefix}web:${tag}", (Join-Path $Repo "web"))
    if ($cacheFlag) { $buildArgs = @($cacheFlag) + $buildArgs }
    & $Engine @buildArgs
    Write-Host "✓  web built" -ForegroundColor Green
} else {
    Write-Host "→  Skipping build (use -Build to rebuild)" -ForegroundColor Yellow
}

# ── 4. Start the stack ─────────────────────────────────────────────────────────
Write-Host "→  Starting stack …" -ForegroundColor Cyan
if ($Engine -eq "podman") {
    & podman-compose --env-file $EnvFile up -d
} else {
    # Docker Compose v2 needs extra_hosts for host access — add it inline
    & docker compose --env-file $EnvFile up -d
}

# ── 5. Wait for Caddy ─────────────────────────────────────────────────────────
Write-Host "→  Waiting for Caddy HTTPS on :8443 …" -ForegroundColor Cyan
$n = 0
while ($n -lt 60) {
    try {
        $req = [Net.HttpWebRequest]::Create("https://localhost:8443")
        $req.ServerCertificateValidationCallback = { $true }
        $req.Timeout = 2000
        $resp = $req.GetResponse()
        $resp.Close()
        Write-Host "✓  Caddy is up" -ForegroundColor Green
        break
    } catch {
        $n++; Start-Sleep 2
    }
}
if ($n -ge 60) {
    Write-Warning "Caddy didn't respond after 120s. Check logs:"
    if ($Engine -eq "podman") { Write-Host "  podman-compose --env-file $EnvFile logs caddy" }
    else { Write-Host "  docker compose --env-file $EnvFile logs caddy" }
}

Write-Host ""
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
Write-Host "  Auralynq is ready" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Chat UI:     https://localhost:8443"
Write-Host "  ModelFit:    https://localhost:8443/modelfit"
Write-Host "  API health:  https://localhost:8443/api/health"
Write-Host ""
Write-Host "  Self-signed cert: click Advanced → Proceed to localhost" -ForegroundColor Yellow
Write-Host ""
Write-Host "  Logs:   podman-compose --env-file .env.podman.windows logs -f"
Write-Host "  Stop:   podman-compose --env-file .env.podman.windows down"
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
